create table if not exists configuracion_clinica (
    id integer generated by default as identity primary key,
    nombre varchar(150) not null default 'MediPortal',
    slug varchar(80) not null unique default 'mediportal',
    timezone varchar(80) not null default 'America/Argentina/Buenos_Aires',
    telefono varchar(50),
    email varchar(200),
    direccion varchar(250),
    sitio_web varchar(250),
    logo_url varchar(500),
    color_primario varchar(20) default '#0284c7',
    duracion_slot_minutos integer not null default 20 check (duracion_slot_minutos > 0),
    hora_inicio_manana varchar(5) not null default '08:00',
    hora_fin_manana varchar(5) not null default '14:00',
    hora_inicio_tarde varchar(5) not null default '14:00',
    hora_fin_tarde varchar(5) not null default '19:00',
    permite_sobreturnos boolean not null default true,
    permite_turnos_particulares boolean not null default true,
    requiere_aprobacion_pacientes boolean not null default false,
    cancelacion_horas_minimas integer not null default 24 check (cancelacion_horas_minimas >= 0),
    upload_dir_resultados varchar(300) not null default 'uploads/resultados',
    activo boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table if not exists pacientes (
    id integer generated by default as identity primary key,
    dni varchar(20) not null unique,
    nombre varchar(100) not null,
    apellido varchar(100) not null,
    email varchar(200),
    telefono varchar(50),
    fecha_nacimiento varchar(20),
    obra_social varchar(100),
    password_hash varchar(256) not null,
    primer_login boolean not null default true,
    activo boolean not null default true,
    aprobado boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table if not exists usuarios_staff (
    id integer generated by default as identity primary key,
    nombre varchar(100) not null,
    apellido varchar(100) not null,
    email varchar(200) not null unique,
    password_hash varchar(256) not null,
    rol varchar(50) not null default 'recepcion',
    activo boolean not null default true,
    atiende_particular boolean not null default true,
    created_at timestamp with time zone not null default now(),
    constraint usuarios_staff_rol_chk check (rol in ('admin', 'recepcion', 'profesional'))
);

create table if not exists especialidades (
    id integer generated by default as identity primary key,
    nombre varchar(120) not null unique,
    descripcion text,
    activa boolean not null default true,
    orden integer not null default 0,
    created_at timestamp with time zone not null default now()
);

create table if not exists obras_sociales (
    id integer generated by default as identity primary key,
    nombre varchar(160) not null unique,
    tipo varchar(60) not null default 'obra_social',
    activa boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table if not exists profesionales_especialidades (
    id integer generated by default as identity primary key,
    profesional_id integer not null references usuarios_staff(id) on delete cascade,
    especialidad_id integer not null references especialidades(id) on delete cascade,
    nombre_publico varchar(160) not null,
    turno varchar(20) not null default 'manana',
    activo boolean not null default true,
    created_at timestamp with time zone not null default now(),
    constraint profesionales_especialidades_turno_chk check (turno in ('manana', 'tarde')),
    constraint uq_profesional_especialidad unique (profesional_id, especialidad_id)
);

create table if not exists turnos (
    id integer generated by default as identity primary key,
    paciente_id integer not null references pacientes(id) on delete cascade,
    fecha varchar(20) not null,
    hora varchar(10) not null,
    especialidad varchar(100) not null,
    profesional varchar(100),
    estado varchar(50) not null default 'pendiente',
    tipo varchar(20) not null default 'normal',
    tipo_consulta varchar(20) not null default 'obra_social',
    observaciones text,
    created_at timestamp with time zone not null default now(),
    created_by varchar(100),
    constraint turnos_estado_chk check (estado in ('pendiente', 'confirmado', 'cancelado', 'completado')),
    constraint turnos_tipo_chk check (tipo in ('normal', 'sobreturno')),
    constraint turnos_tipo_consulta_chk check (tipo_consulta in ('obra_social', 'particular'))
);

create table if not exists turno_logs (
    id integer generated by default as identity primary key,
    turno_id integer not null references turnos(id) on delete cascade,
    accion varchar(50) not null,
    descripcion text not null,
    realizado_por varchar(100) not null,
    created_at timestamp with time zone not null default now()
);

create table if not exists resultados (
    id integer generated by default as identity primary key,
    paciente_id integer not null references pacientes(id) on delete cascade,
    titulo varchar(200) not null,
    descripcion text,
    archivo_nombre varchar(300),
    archivo_path varchar(500),
    fecha_estudio varchar(20),
    subido_por varchar(100),
    created_at timestamp with time zone not null default now()
);

create table if not exists avisos (
    id integer generated by default as identity primary key,
    titulo varchar(200) not null,
    contenido text not null,
    tipo varchar(20) not null default 'info',
    activo boolean not null default true,
    orden integer not null default 0,
    created_at timestamp with time zone not null default now(),
    constraint avisos_tipo_chk check (tipo in ('info', 'warning', 'importante'))
);

create table if not exists notificaciones (
    id integer generated by default as identity primary key,
    paciente_id integer not null references pacientes(id) on delete cascade,
    titulo varchar(200) not null,
    mensaje text not null,
    tipo varchar(40) not null default 'info',
    leido boolean not null default false,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_pacientes_dni on pacientes(dni);
create index if not exists idx_usuarios_staff_email on usuarios_staff(email);
create index if not exists idx_turnos_fecha_hora on turnos(fecha, hora);
create index if not exists idx_turnos_paciente on turnos(paciente_id);
create index if not exists idx_turnos_profesional on turnos(profesional);
create index if not exists idx_turnos_estado on turnos(estado);
create index if not exists idx_turno_logs_turno on turno_logs(turno_id);
create index if not exists idx_resultados_paciente on resultados(paciente_id);
create index if not exists idx_notificaciones_paciente on notificaciones(paciente_id);

create unique index if not exists uq_turno_profesional_activo
on turnos(fecha, hora, profesional)
where profesional is not null and profesional <> '' and estado in ('pendiente', 'confirmado');

create or replace function set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists trg_configuracion_clinica_updated_at on configuracion_clinica;
create trigger trg_configuracion_clinica_updated_at
before update on configuracion_clinica
for each row
execute function set_updated_at();
